-- Supabase schema for vTOC telemetry entities.
-- This script mirrors the SQLAlchemy models defined in backend/app/models.py.

create table if not exists public.stations (
    id integer generated by default as identity primary key,
    slug varchar(100) not null unique,
    name varchar(255) not null,
    description text,
    timezone varchar(100) not null default 'UTC',
    telemetry_schema varchar(255),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_stations_slug on public.stations (slug);

create table if not exists public.telemetry_sources (
    id integer generated by default as identity primary key,
    station_id integer references public.stations(id) on delete set null,
    name varchar(255) not null unique,
    slug varchar(100) not null unique,
    source_type varchar(100) not null,
    description text,
    is_active boolean not null default true,
    connection_mode varchar(50) not null default 'online',
    configuration jsonb,
    last_ingested_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_telemetry_sources_slug on public.telemetry_sources (slug);
create index if not exists ix_telemetry_sources_station_id on public.telemetry_sources (station_id);

create table if not exists public.telemetry_events (
    id integer generated by default as identity primary key,
    source_id integer not null references public.telemetry_sources(id) on delete cascade,
    station_id integer references public.stations(id) on delete set null,
    event_time timestamptz not null default timezone('utc', now()),
    received_at timestamptz not null default timezone('utc', now()),
    latitude double precision,
    longitude double precision,
    altitude double precision,
    heading double precision,
    speed double precision,
    payload jsonb,
    raw_data text,
    status varchar(50) not null default 'received'
);

create index if not exists ix_telemetry_events_event_time on public.telemetry_events (event_time);
create index if not exists ix_telemetry_events_source_id on public.telemetry_events (source_id);
create index if not exists ix_telemetry_events_station_id on public.telemetry_events (station_id);

create table if not exists public.station_assignments (
    id integer generated by default as identity primary key,
    station_id integer not null references public.stations(id) on delete cascade,
    source_id integer not null references public.telemetry_sources(id) on delete cascade,
    role varchar(100) not null default 'primary',
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_station_assignments_station_id on public.station_assignments (station_id);
create index if not exists ix_station_assignments_source_id on public.station_assignments (source_id);
