# Agent Configuration

agents:
  monitor:
    enabled: true
    schedule: "*/5 * * * *"  # Every 5 minutes
    description: "Monitor system health and metrics"

  analyzer:
    enabled: true
    schedule: "*/10 * * * *"  # Every 10 minutes
    description: "Analyze intelligence reports and mission data"

  executor:
    enabled: true
    schedule: "*/15 * * * *"  # Every 15 minutes
    description: "Execute automated tasks and workflows"

sources:
  adsb:
    type: adsb
    enabled: false
    schedule: "*/2 * * * *"
    mode: online
    backend_url: "http://backend:8000"
    api_url: "https://api.adsbexchange.com/v2/data/"  # Replace with provider endpoint
    params:
      icao: "abcd12"
    log_path: "/data/adsb.log"

  ais:
    type: ais
    enabled: false
    schedule: 10  # minutes
    mode: online
    backend_url: "http://backend:8000"
    api_url: "https://ais-provider.example/api/v1/vessels"
    api_token: "${AIS_API_TOKEN}"
    capture_path: "/data/ais_capture.nmea"

  aprs:
    type: aprs
    enabled: false
    schedule: 5
    mode: offline
    backend_url: "http://backend:8000"
    igate_url: "https://aprs.fi/igate/feed/"
    packet_log: "/data/aprs_packets.log"

  tle:
    type: tle
    enabled: false
    schedule: "30m"
    backend_url: "http://backend:8000"
    tle_url: "https://celestrak.com/NORAD/elements/active.txt"
    tle_file: "/data/active.tle"

  rtlsdr:
    type: rtlsdr
    enabled: false
    schedule: 1
    mode: offline
    backend_url: "http://backend:8000"
    stream_url: "rtl_tcp://127.0.0.1:1234"
    iq_recording: "/data/rtlsdr_capture.iq"

  meshtastic:
    type: meshtastic
    enabled: false
    schedule: "15m"
    backend_url: "http://backend:8000"
    http_bridge: "http://meshtastic.local:4403/api/v1/telemetry"
    json_log: "/data/meshtastic.log"

  gps:
    type: gps
    enabled: false
    schedule: 2
    backend_url: "http://backend:8000"
    mode: offline
    ntrip_endpoint: "ntrip://caster.example:2101/MOUNT"
    gpx_file: "/data/track.gpx"
    nmea_log: "/data/track.nmea"

settings:
  api_url: "http://backend:8000"
  retry_attempts: 3
  retry_delay: 5
  log_level: "INFO"
