# Agent Configuration

agents:
  monitor:
    enabled: true
    schedule: "*/5 * * * *"  # Every 5 minutes
    description: "Monitor system health and metrics"
  
  analyzer:
    enabled: true
    schedule: "*/10 * * * *"  # Every 10 minutes
    description: "Analyze intelligence reports and mission data"
  
  executor:
    enabled: true
    schedule: "*/15 * * * *"  # Every 15 minutes
    description: "Execute automated tasks and workflows"

settings:
  api_url: "http://backend:8000"
  retry_attempts: 3
  retry_delay: 5
  log_level: "INFO"
