#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create extensions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";
    
    -- Station schemas
    CREATE SCHEMA IF NOT EXISTS toc_s1 AUTHORIZATION $POSTGRES_USER;
    CREATE SCHEMA IF NOT EXISTS toc_s2 AUTHORIZATION $POSTGRES_USER;
    CREATE SCHEMA IF NOT EXISTS toc_s3 AUTHORIZATION $POSTGRES_USER;
    CREATE SCHEMA IF NOT EXISTS toc_s4 AUTHORIZATION $POSTGRES_USER;

    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
    ALTER ROLE $POSTGRES_USER SET search_path TO public;
EOSQL
