erDiagram
  if {
    integer id
    varchar(100) slug
    varchar(255) name
    text description
    varchar(100) timezone
    varchar(255) telemetry_schema
    timestamptz created_at
    timestamptz updated_at
  }
