"""Service utilities."""

from .hardware.manager import (
    AdsbConfig,
    AdsbToggleRequest,
    BaseStationConfig,
    BaseStationRegistration,
    GpsTestRequest,
    GpsTestResult,
    H4MImportRequest,
    H4MImportResult,
    HardwareConfigStore,
    HardwareConfiguration,
    HardwareHealthSummary,
    HardwareManager,
    HardwareOperationError,
    HardwareStatus,
    SerialPortInfo,
    get_hardware_manager,
)
from .supabase import (
    SupabaseApiError,
    SupabaseRepository,
    get_station_context,
    get_supabase_repository,
    resolve_station_slug,
)

__all__ = [
    "AdsbConfig",
    "AdsbToggleRequest",
    "BaseStationConfig",
    "BaseStationRegistration",
    "GpsTestRequest",
    "GpsTestResult",
    "H4MImportRequest",
    "H4MImportResult",
    "HardwareConfigStore",
    "HardwareConfiguration",
    "HardwareHealthSummary",
    "HardwareManager",
    "HardwareOperationError",
    "HardwareStatus",
    "SerialPortInfo",
    "get_hardware_manager",
    "SupabaseApiError",
    "SupabaseRepository",
    "get_station_context",
    "get_supabase_repository",
    "resolve_station_slug",
]
