name: Fly Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - live

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy to Fly.io
        env:
          TAG: ${{ github.sha }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: scripts/fly_deploy.sh
