name: Fly Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - live

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy to Fly.io
        env:
          TAG: ${{ github.sha }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: scripts/fly_deploy.sh

  verify-sync:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Check Fly.io deployment health
        run: |
          curl -fsSL https://vtoc.pr-cybr.com/healthz
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upsert prod → main sync PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = require('path');
            const upsert = require(path.join(process.cwd(), '.github/scripts/upsert-prod-sync-pr.js'));
            await upsert({ github, context, core });
