name: Live Release PR Gate

on:
  pull_request:
    branches:
      - live
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  packages: write

jobs:
  tests:
    if: github.head_ref == 'stage'
    uses: ./.github/workflows/reusable-tests.yml

  publish:
    if: github.head_ref == 'stage'
    needs: tests
    uses: ./.github/workflows/reusable-build-containers.yml
    secrets: inherit

  summary:
    name: Release pipeline summary
    needs:
      - tests
      - publish
    if: github.head_ref == 'stage' && always()
    runs-on: ubuntu-latest
    steps:
      - name: Publish summary
        env:
          TESTS_RESULT: ${{ needs.tests.result }}
          PUBLISH_RESULT: ${{ needs.publish.result }}
          SCAN_STATUS: ${{ needs.publish.outputs.scan_status }}
          PUSH_STATUS: ${{ needs.publish.outputs.push_status }}
        run: |
          tests_line="- ❌ Tests ${TESTS_RESULT}"
          if [[ "${TESTS_RESULT}" == "success" ]]; then
            tests_line="- ✅ Tests passed"
          fi
          if [[ "${PUBLISH_RESULT}" != "success" ]]; then
            scan_line="- ❌ Container scans incomplete (${PUBLISH_RESULT})"
            push_line="- ❌ Image pushes incomplete (${PUBLISH_RESULT})"
          else
            if [[ "${SCAN_STATUS}" == "passed" ]]; then
              scan_line="- ✅ Container vulnerability scans passed"
            else
              scan_line="- ⚠️ Container vulnerability scans status unavailable"
            fi
            if [[ "${PUSH_STATUS}" == "passed" ]]; then
              push_line="- ✅ Multi-arch image pushes completed"
            else
              push_line="- ⚠️ Multi-arch image push status unavailable"
            fi
          fi
          {
            echo "## Release Pipeline Summary"
            echo
            echo "${tests_line}"
            echo "${scan_line}"
            echo "${push_line}"
          } >> "$GITHUB_STEP_SUMMARY"
